import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BRIEF_MARKDOWN, printBrief } from "#dist/brief.js";

const packageJson = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "package.json"),
    "utf-8",
  ),
) as { version: string };

test("BRIEF_MARKDOWN is a non-empty string", () => {
  assert.equal(typeof BRIEF_MARKDOWN, "string");
  assert.ok(BRIEF_MARKDOWN.length > 0);
});

test("BRIEF_MARKDOWN contains all required section headers", () => {
  const requiredSections = [
    "# Dangeresque Workflow",
    "## Prime Directives",
    "### Quality Gates",
    "### Honest Scoping",
    "## The Loop",
    "## The One Hard Rule",
    "## Creating Issues",
    "## Dispatching a Run",
    "## Reading Results",
    "## Staging Guidance",
    "## Merging or Discarding",
    "## Monitoring a Run",
    "## Modes",
    "## What NOT to Do",
    "## Pointers",
  ];
  for (const heading of requiredSections) {
    assert.ok(
      BRIEF_MARKDOWN.includes(heading),
      `missing section header: ${heading}`,
    );
  }
});

test("BRIEF_MARKDOWN covers the Prime Directives named items", () => {
  const namedItems = [
    "VERIFY-BEFORE",
    "VERIFY-AFTER",
    "NO-BANDAID",
    "ONE-PATH",
    "FILE-IMMEDIATELY",
    "INVESTIGATE-ALWAYS",
  ];
  for (const item of namedItems) {
    assert.ok(
      BRIEF_MARKDOWN.includes(item),
      `missing Prime Directive item: ${item}`,
    );
  }
});

test("BRIEF_MARKDOWN ends with version footer matching package.json", () => {
  const expected = `Generated by dangeresque v${packageJson.version}.`;
  assert.ok(
    BRIEF_MARKDOWN.includes(expected),
    `expected footer '${expected}' in BRIEF_MARKDOWN`,
  );
});

test("BRIEF_MARKDOWN covers the core command surface", () => {
  const commands = [
    "dangeresque run --issue",
    "dangeresque results",
    "dangeresque stage",
    "dangeresque merge",
    "dangeresque discard",
    "dangeresque logs",
    "dangeresque status",
  ];
  for (const cmd of commands) {
    assert.ok(BRIEF_MARKDOWN.includes(cmd), `missing command reference: ${cmd}`);
  }
});

test("BRIEF_MARKDOWN references the project-local AFK_WORKER_RULES and PERMISSIONS docs", () => {
  assert.ok(BRIEF_MARKDOWN.includes(".dangeresque/AFK_WORKER_RULES.md"));
  assert.ok(BRIEF_MARKDOWN.includes("docs/PERMISSIONS.md"));
});

test("BRIEF_MARKDOWN documents the canonical/.local.md overlay and DANGERESQUE.md ownership", () => {
  assert.ok(
    BRIEF_MARKDOWN.includes(".local.md"),
    "expected BRIEF_MARKDOWN to mention the .local.md companion pattern",
  );
  assert.ok(
    BRIEF_MARKDOWN.includes("Do not edit `.dangeresque/DANGERESQUE.md`"),
    "expected BRIEF_MARKDOWN to warn against editing DANGERESQUE.md directly",
  );
});

test("printBrief writes BRIEF_MARKDOWN to stdout without side effects", () => {
  const chunks: Buffer[] = [];
  const originalWrite = process.stdout.write.bind(process.stdout);
  const originalExit = process.exit;

  let exitCalled = false;
  (process as unknown as { exit: (code?: number) => void }).exit = () => {
    exitCalled = true;
  };
  process.stdout.write = ((chunk: string | Uint8Array) => {
    chunks.push(Buffer.from(chunk));
    return true;
  }) as typeof process.stdout.write;

  try {
    printBrief();
  } finally {
    process.stdout.write = originalWrite;
    (process as unknown as { exit: typeof process.exit }).exit = originalExit;
  }

  const output = Buffer.concat(chunks).toString("utf-8");
  assert.equal(output, BRIEF_MARKDOWN);
  assert.equal(exitCalled, false, "printBrief must not call process.exit");
});
