import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { BRIEF_MARKDOWN, printBrief } from "#dist/brief.js";

const packageJson = JSON.parse(
  readFileSync(
    join(
      dirname(fileURLToPath(import.meta.url)),
      "..",
      "..",
      "..",
      "package.json",
    ),
    "utf-8",
  ),
) as { version: string };

test("BRIEF_MARKDOWN is a non-empty string", () => {
  assert.equal(typeof BRIEF_MARKDOWN, "string");
  assert.ok(BRIEF_MARKDOWN.length > 0);
});

test("BRIEF_MARKDOWN contains all required section headers", () => {
  const requiredSections = [
    "# Dangeresque Workflow",
    "### Honest Scoping",
    "## The Standard Loop",
    "## The One Hard Rule",
    "## Creating Issues",
    "## Quick Command Reference",
    "## Modes",
    "## What NOT to Do",
    "## Pointers",
  ];
  for (const heading of requiredSections) {
    assert.ok(
      BRIEF_MARKDOWN.includes(heading),
      `missing section header: ${heading}`,
    );
  }
});

test("BRIEF_MARKDOWN ends with version footer matching package.json", () => {
  const expected = `Generated by dangeresque v${packageJson.version}.`;
  assert.ok(
    BRIEF_MARKDOWN.includes(expected),
    `expected footer '${expected}' in BRIEF_MARKDOWN`,
  );
});

test("BRIEF_MARKDOWN covers the workflow-relevant command surface", () => {
  // These verbs drive the standard loop. Setup/utility verbs (init, allow,
  // stats, clean, brief itself) and configuration flags are intentionally
  // deferred to `dangeresque --help` to prevent the drift that produced
  // commit a7d4e20.
  const commands = [
    "dangeresque run --issue",
    "dangeresque review <branch>",
    "dangeresque resume <branch>",
    "dangeresque results",
    "dangeresque stage",
    "dangeresque merge",
    "dangeresque discard",
    "dangeresque stop",
    "dangeresque logs",
    "dangeresque status",
  ];
  for (const cmd of commands) {
    assert.ok(
      BRIEF_MARKDOWN.includes(cmd),
      `missing command reference: ${cmd}`,
    );
  }
});

test("BRIEF_MARKDOWN delegates command surface to `dangeresque --help`", () => {
  // Drift firewall: the brief must explicitly tell the orchestrator that the
  // full command list lives in --help. Otherwise readers treat the brief as
  // exhaustive and the next added command goes unnoticed (a7d4e20).
  assert.ok(
    BRIEF_MARKDOWN.includes("dangeresque --help"),
    "BRIEF_MARKDOWN must reference `dangeresque --help` as the canonical command surface",
  );
});

test("BRIEF_MARKDOWN warns merge/discard have asymmetric artifact behavior", () => {
  // The orchestrator-confusion symptom from #64: discard silently destroys
  // the run report. Brief must spell out merge=keeps / discard=deletes near
  // the loop and again in the cleanup section.
  assert.ok(
    /Merge keeps the run report\. Discard deletes it\./.test(BRIEF_MARKDOWN),
    "BRIEF_MARKDOWN must contain the merge/discard asymmetry one-liner near the loop",
  );
  assert.ok(
    BRIEF_MARKDOWN.includes("KEEPS the run report"),
    "BRIEF_MARKDOWN merge command line must disclose artifact-keep behavior",
  );
  assert.ok(
    BRIEF_MARKDOWN.includes("DELETES the run report"),
    "BRIEF_MARKDOWN discard command line must disclose artifact-delete behavior",
  );
});

test("BRIEF_MARKDOWN teaches both crash-recovery verbs and which phase each covers", () => {
  // The whole failure mode issue #110 exists to fix is an orchestrator reading
  // a dead worker's FAILED comment and reaching for `discard`, which deletes
  // the uncommitted diff. The brief has to name the other exit, and has to make
  // the review/resume split unambiguous.
  assert.ok(BRIEF_MARKDOWN.includes("dangeresque resume <branch>"));
  assert.ok(
    /\*\*If a review dies, do NOT re-dispatch the worker\.\*\*/.test(BRIEF_MARKDOWN),
    "review-death recovery paragraph missing",
  );
  assert.ok(
    /\*\*If a WORKER dies, do NOT discard the worktree\.\*\*/.test(BRIEF_MARKDOWN),
    "worker-death recovery paragraph missing",
  );
  assert.ok(
    BRIEF_MARKDOWN.includes("`review` needs a worker that FINISHED, `resume` needs one that did NOT"),
    "brief must state the exclusivity rule that tells an operator which verb to pick",
  );
  assert.ok(
    BRIEF_MARKDOWN.includes("resumed_from"),
    "brief must name the lineage field linking a resumed run to the attempt it continued",
  );
});

test("BRIEF_MARKDOWN references the project-local AFK_WORKER_RULES and PERMISSIONS docs", () => {
  assert.ok(BRIEF_MARKDOWN.includes(".dangeresque/AFK_WORKER_RULES.md"));
  assert.ok(BRIEF_MARKDOWN.includes("docs/PERMISSIONS.md"));
});

test("BRIEF_MARKDOWN documents the canonical/.local.md overlay and DANGERESQUE.md ownership", () => {
  assert.ok(
    BRIEF_MARKDOWN.includes(".local.md"),
    "expected BRIEF_MARKDOWN to mention the .local.md companion pattern",
  );
  assert.ok(
    BRIEF_MARKDOWN.includes("Do not edit `.dangeresque/DANGERESQUE.md`"),
    "expected BRIEF_MARKDOWN to warn against editing DANGERESQUE.md directly",
  );
});

test("printBrief writes BRIEF_MARKDOWN to stdout without side effects", () => {
  const chunks: Buffer[] = [];
  const originalWrite = process.stdout.write.bind(process.stdout);
  const originalExit = process.exit;

  let exitCalled = false;
  (process as unknown as { exit: (code?: number) => void }).exit = () => {
    exitCalled = true;
  };
  process.stdout.write = ((chunk: string | Uint8Array) => {
    chunks.push(Buffer.from(chunk));
    return true;
  }) as typeof process.stdout.write;

  try {
    printBrief();
  } finally {
    process.stdout.write = originalWrite;
    (process as unknown as { exit: typeof process.exit }).exit = originalExit;
  }

  const output = Buffer.concat(chunks).toString("utf-8");
  assert.equal(output, BRIEF_MARKDOWN);
  assert.equal(exitCalled, false, "printBrief must not call process.exit");
});
